version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: "monday"
      time: "05:08"
      timezone: "Europe/Stockholm"
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      go:
        patterns:
          - "*"  # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "monday"
      time: "05:08"
      timezone: "Europe/Stockholm"
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: weekly
      day: "monday"
      time: "05:08"
      timezone: "Europe/Stockholm"
