run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - dupl # allow duplication
    - funlen # allow long functions
    - gomnd # allow some magic numbers
    - wsl # unwanted amount of whitespace
    - godox # allow TODOs
    - interfacer # deprecated by the author for having too many false positives
    - gocognit # allow higher cognitive complexity
    - testpackage # unwanted convention
    - nestif # allow deep nesting
    - unparam # allow constant parameters
    - goerr113 # allow "dynamic" errors
    - exhaustive # TODO: fix and enable
    - gofumpt # TODO: enable when whitespace diff issue is resolved
    - maligned # deprecated
    - scopelint # deprecated
    - golint # deprecated
    - paralleltest # don't require that test methods can be run in parallel
    - nlreturn # don't require newline before return
    - exhaustivestruct # allow zero initialization
