steps:
  - name: gcr.io/einride/gcb-setup
    volumes:
      - name: ssh
        path: /root/.ssh
    env:
      - BRANCH_NAME=$BRANCH_NAME
      - REPO_NAME=$REPO_NAME

  - name: gcr.io/einride/gcb-go:1.13
    entrypoint: make
    volumes:
      - name: ssh
        path: /root/.ssh
