# Code generated by go.einride.tech/mage-tools. DO NOT EDIT.
# To learn more, see .mage/magefile.go and https://github.com/einride/mage-tools.

.DEFAULT_GOAL := all

magefile := .mage/tools/bin/magefile

$(magefile): .mage/go.mod .mage/*.go
	@cd .mage && go run go.einride.tech/mage-tools/cmd/build

.PHONY: clean-mage-tools
clean-mage-tools:
	@git clean -fdx .mage/tools

.PHONY: all
all: $(magefile)
	@$(magefile) All

.PHONY: convco-check
convco-check: $(magefile)
	@$(magefile) ConvcoCheck

.PHONY: format-markdown
format-markdown: $(magefile)
	@$(magefile) FormatMarkdown

.PHONY: format-yaml
format-yaml: $(magefile)
	@$(magefile) FormatYaml

.PHONY: git-verify-no-diff
git-verify-no-diff: $(magefile)
	@$(magefile) GitVerifyNoDiff

.PHONY: go-mod-tidy
go-mod-tidy: $(magefile)
	@$(magefile) GoModTidy

.PHONY: go-test
go-test: $(magefile)
	@$(magefile) GoTest

.PHONY: golangci-lint
golangci-lint: $(magefile)
	@$(magefile) GolangciLint

.PHONY: goreview
goreview: $(magefile)
	@$(magefile) Goreview
